config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  get '/search', to: 'hashtags#search', as: 'search'
  resources :hashtags
  get '/search_result', to: 'hashtags#search_result', as: 'search_result'
  resources :hashtags
  post '/users/:user_id/pictures/:picture_id/likes/:icon_id', to: 'likes#create'
  get '/index', to: 'application#index'
  get '/users', to: 'users#redirect', as: 'redirect'
  resources :sessions, only: [:new, :create]
  delete '/sessions', to: 'sessions#destroy', as: 'destroy_session'
  get'/users/discover', to: 'users#discover', as: 'discover'
  get '/users/:id/followers', to: 'users#followers', as: "followers"
  get '/users/:id/followees', to: 'users#followees', as: "followees"

  get '/users/index', to: 'users#index'
  get '/users/login', to: 'users#login'
  get '/users/signup', to: 'users#signup'
  post '/users/check_user', to: 'users#check_user'

  # get '/users/user_information', to: 'users#user_information', as: 'info'
  resources :users do
    post '/followings', to: 'followings#create', as: 'create_following'
    delete '/followings', to: 'followings#destroy', as: 'unfollow'
    resources :pictures do
      resources :comments
      post '/likes', to: 'likes#create', as: 'create_like'
      resources :likes

    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  validates_confirmation_of :password
  has_many :follower_follows, class_name: "Following", foreign_key: :followee_id
  has_many :followers, through: :follower_follows, source: :follower
  has_many :followee_follows, class_name: "Following", foreign_key: :follower_id
  has_many :followees, through: :followee_follows, source: :followee
  has_many :likes
  has_many :pictures
  has_many :comments, through: :pictures
  # has_many :donatees, class_name: "Relationship",
  # has_many :hashtags
  has_secure_password
  has_one_attached :img_url
  # validates :username, presence: true
  # validates :username, uniqueness: true
  # validates :username, length: {minimum: 3, maximum: 15}
  # validates :name, presence: true
  # validates :password, presence: true
  # validates :password, length: {minimum: 6, maximum: 20}, allow_nil: true

  # def password=(plaintext_password)
  #   self.password_digest = BCrypt::Password.create(plaintext_password)
  # end

  def authenticate(plaintext_password)
    BCrypt::Password.new(self.password_digest) == plaintext_password
  end

  def add_like

  end

  def post_picture

  end

  def set_img_url
    self.img_url.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'snowflake.png')), filename: 'snowflake.png', content_type: 'image/png')
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show,:edit, :update, :destroy, :followers, :followees]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params(:name, :username, :password, :password_confirmation))
    @user.set_img_url
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def check_user
    @user = User.find_by(username: params[:user][:username])
    if  @user
      if (params[:user][:password] == @user.password)
          redirect_to @user
      end
    else
      render :login
    end
  end

  def show

    if current_user
      @current_user_does_not_follow = !current_user_follows?
      @current_user_follows = current_user_follows?
      @authorization =  authorization?
    else
      render :index
    end
  end

  def edit

  end

  def update
    if @user.update(user_params(:name, :password, :bio, :email, :number, :gender, :img_url))
      redirect_to @user
    else
      render :edit
    end
  end

  def login
    @user = User.new

  end


  def index
    @current_user = current_user
    if @current_user
      @followees = current_user.followees
      @pic = []
      @followees.each do |followee|
        @pic << followee.pictures
      end
      @pic.flatten!
      @pic.sort_by! {|pic| pic.created_at}
    end
  end

  def destroy
    @user.destroy
  end


  def redirect
      redirect_to session[:previous_url]
  end

  def discover
    @users = User.all
    # @users = User.all.select do |user|
    #   user.id != find_current_user.id
    # end
  end

# http://localhost:3000/users/1/pictures/1
  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params(*args)
    params.require(:user).permit(*args)
  end




end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.erb
<%= form_for @user do |f| %>
<%= f.label :username  %>
<%= f.text_field :username %>
<%= f.password_field :password  %>
<%= f.password_field :password_confirmation %>
<%= f.submit%>
<%end%>


#edit later for edit and update

app/views/users/discover.erb
<h3 class="header_text">COMMUNITY</h1>
<div class="discover_container">




<% @users.each do |user| %>
<div class="discover_user">


  <a href= <%="/users/#{user.id}"%> >
    <%= image_tag user.img_url, class: "user_profile_pic" %></a>

    <div class="username">
      <%= user.name %>
    </div>
    </div>
<% end %>


</div>

app/views/users/edit.erb
<div class="centering_container">
  <div class="form_container">
    <%= form_for @user do |f| %>
    <div>
      <%= f.label :name, class: "label"  %>
      <%= f.text_field :name, class: "picture_edit_form_input" %>
    </div>
    <div>
      <%= f.label "Profile Picture", class: "label"   %>
      <%= f.file_field :img_url, class: "picture_edit_form_input" %>
    </div>
    <div>
      <%= f.label :bio, class: "label"  %>
      <%= f.text_area :bio, class: "picture_edit_form_input" %>
    </div>
    <div>
      <%= f.label :email, class: "label"   %>
      <%= f.email_field :email, class: "picture_edit_form_input" %>
    </div>
    <div>
      <%= f.label :number, class: "label"   %>
      <%= f.telephone_field :number, place_holder: 'xxx-xxx-xxxx', class: "picture_edit_form_input" %>
    </div>
    <div>
      <%= f.label :gender, class: "label"   %>
      <%= f.select :gender, ["Male", "Female", "Non Binary"] %>
    </div>

    <div class="button-container">
      <%= f.submit class: "edit_form_buttons"%>
     <button class="edit_form_buttons" type="button" name="button"><%= link_to "Back", @user %></button>
    </div>

    <%end%>
  </div>
</div>

app/views/users/followees.erb
<div class="discover_container">
<% @user.followees.each do |followee| %>

<div class="discover_user">

  <a href= <%="/users/#{followee.id}"%> >
    <%= image_tag followee.img_url, class: "user_profile_pic" %></a>

    <div class="username">
    <%= followee.name %>
    </div>
</div>


<% end %>

</div>

app/views/users/followers.erb
<div class="discover_container">
<% @user.followers.each do |follower| %>
<div class="discover_user">
  <a href= <%="/users/#{follower.id}"%> >
    <%= image_tag follower.img_url, class: "user_profile_pic" %></a>

    <div class="username">
    <%= follower.name %>
    </div>
</div>
<% end %>

</div>

app/views/users/index.erb
<div class="page_container">

  <% if @current_user == nil %>

    <div class="register_container">

      <div class="enter log">
        <%= link_to "Log In", new_session_path, :class => "not_logged_in log enter" %>
      </div>

      <div class="enter ">
        <%= link_to "Sign Up", new_user_path,:class => "not_logged_in sign enter"  %>
      </div>

    </div>

  <% else %>
    <div class="centering_container">

      <% if @current_user.followees.count == 0  %>

        <div class="empty_feed">
          <p class="sorry red">Sorry!</p>
          <p class="empty_feed_inner_message">You don't follow anyone yet! Click <%= link_to "here", discover_path, class: "link"%> to discover some users to follow. 🎄  </p>
        </div>

      <% else %>

        <div class="index_post_container">
          <% @pic.take(20).each do |pic| %>
            <div class="index_post">

              <div class="picture_author">
                <%= image_tag pic.user.img_url, width: 50, height: 50, class: "index_user_pic"%> <%= link_to pic.user.username, pic.user, :class => "feed_username" %>
              </div>

              <div class="align_picture_and_comments">

                <div class="index_pictures">
                  <a href= <%="/users/#{pic.user.id}/pictures/#{pic.id}"%> >
                    <%= image_tag pic.img_url, class: "index_pictures" %></a>
                </div>

                <div class="index_picture_info">
                  <%= link_to pic.user.username, pic.user, :class => "username" %>
                    <div class="picture_description">
                      <%= pic.description%>
                    </div>
                </div>

                <div class="index_comments_container">
                  <% pic.comments.take(5).each do |comment| %>
                    <div class="comment">
                      <%= link_to comment.user.username, comment.user %> <%= comment.content %>
                    </div>
                  <% end %>
                </div>

              </div> <!-- align_picture_and_comments -->
            </div> <!-- index_post -->
          <% end %>
        </div> <!-- index_post_container -->
      <% end %>
    </div> <!-- centering_container -->
  <% end %>
</div> <!-- page_container -->

app/views/users/new.erb
<div class="centering_container">
  <div class="form_container">
<%= form_for @user do |f| %>

  <%= f.label :name, class:"message"  %>
  <%= f.text_field :name, class: "comment_input" %>
  <%= f.label :username, class:"message"  %>
  <%= f.text_field :username, class: "comment_input" %>
  <%= f.label :password, class:"message"  %>
  <%= f.password_field :password, class: "comment_input"  %>
  <%= f.label "Confirm Password", class:"message"  %>
  <%= f.password_field :password_confirmation, class: "comment_input" %>
  <%= f.submit%>
<%end%>

  </div>
</div>

app/views/users/show.erb
<div class="page_container">

<div class="user_top">

  <div class="user_profile_pic">
    <%= image_tag @user.img_url,  :class => "user_profile_pic" %>
    <p> <%= @user.name %> </p>
  </div>

  <div class="show_stats_and_buttons">
  <div class="user_stats">
    <div class="show_posts">
      Posts: <%= @user.pictures.length %>
    </div>
    <div class="show_followers">
      <%= link_to "Followers:", followers_path, class: "link" %>
      <%= @user.followers.length %>
    </div>
    <div class="show_followees">
      <%= link_to "Following:", followees_path, class: "link"  %>
        <%= @user.followees.length %>
    </div>
  </div>




<div class="show_button">
    <% if @authorization %>

      <%= link_to "New Pic", "/users/#{@user.id}/pictures/new", class: "link"  %>

      <%= form_for @user, url: edit_user_path, method: "get" do |f| %>
      <%= f.submit %>
      <% end %>

      <%= link_to "Logout", destroy_session_path, class: "link",  :method => :delete %>


    <% elsif @current_user_does_not_follow %>
    <%= link_to "Follow", "/users/#{@user.id}/followings", method: :post %>

    <% elsif @current_user_follows %>
      <%= link_to "Unfollow", "/users/#{@user.id}/followings", method: :delete %>
    <% end %>
</div>

</div>

</div>

<% if @user.bio %>
  <div class="show_bio">
    "<%= @user.bio %>"
  </div>
<% end %>


<div class="picture_container">
    <% @user.pictures.each do |picture| %>
      <div class="picture_icon">
        <a href= <%="/users/#{@user.id}/pictures/#{picture.id}"%> >
        <%= image_tag picture.img_url, width: 200, height: 200, class: "picture_icon"%></a>
      </div>
    <% end %>
  </div>
</div>