config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  get '/search', to: 'hashtags#search', as: 'search'
  resources :hashtags
  get '/search_result', to: 'hashtags#search_result', as: 'search_result'
  resources :hashtags
  post '/users/:user_id/pictures/:picture_id/likes/:icon_id', to: 'likes#create'
  get '/index', to: 'application#index'
  get '/users', to: 'users#redirect', as: 'redirect'
  resources :sessions, only: [:new, :create]
  delete '/sessions', to: 'sessions#destroy', as: 'destroy_session'
  get'/users/discover', to: 'users#discover', as: 'discover'
  get '/users/:id/followers', to: 'users#followers', as: "followers"
  get '/users/:id/followees', to: 'users#followees', as: "followees"

  get '/users/index', to: 'users#index'
  get '/users/login', to: 'users#login'
  get '/users/signup', to: 'users#signup'
  post '/users/check_user', to: 'users#check_user'

  # get '/users/user_information', to: 'users#user_information', as: 'info'
  resources :users do
    post '/followings', to: 'followings#create', as: 'create_following'
    delete '/followings', to: 'followings#destroy', as: 'unfollow'
    resources :pictures do
      resources :comments
      post '/likes', to: 'likes#create', as: 'create_like'
      resources :likes

    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :picture_hashtags
  has_many :pictures, through: :picture_hashtags
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  def search


  end

  def search_result

    if @hashtag = search_by_hashtag(params[:hashtag][:hashtag])
      @pictures = @hashtag.pictures
    else  
      @error = 1
      render :search
    end

  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/views/hashtags/search.erb
<div class="centering_container">
  <div class="form_container">

<div class="message">
<% if @error %>
    <p class="red">Sorry!</p> <p class="inner_message">There are no pictures with the hashtag you entered. Please search again.</p>
<% end %>



  <%= form_for(Hashtag.new, url: search_result_path, method: :get )  do |f| %>
    <div class="message">
      <%= f.label "Hashtag Search" %>
    </div>
    <div class="comment_input">
      <%= f.text_field :hashtag %>
    </div>
    <div class="search">
      <%= f.submit "Find", class: "search" %>
    </div>

  <% end %>

  </div>
    </div>
</div>

app/views/hashtags/search_result.erb
<div class="centering_container">
  <% if @hashtag%>
    <div class="index_post_container">
      <%@pictures.each do |picture| %>

        <div class="picture_author">
          <%= image_tag picture.user.img_url, width: 50, height: 50, class: "index_user_pic"%> <%= link_to picture.user.username, picture.user, :class => "feed_username" %>
        </div>

        <div class="align_picture_and_comments">

          <div class="index_pictures">
            <a href= <%="/users/#{picture.user.id}/pictures/#{picture.id}"%> >
            <%= image_tag picture.img_url, class: "index_pictures" %></a>
          </div>

          <div class="index_picture_info">
            <%= link_to picture.user.username, picture.user, :class => "username" %>
            <div class="picture_description">
              <%= picture.description%>
            </div>
          </div>

          <div class="index_comments_container">
            <% picture.comments.take(5).each do |comment| %>
              <div class="comment">
                <%= link_to comment.user.username, comment.user %> <%= comment.content   %>
              </div>
            <% end %>
          </div>

        </div> <!-- align_picture_and_comments -->
      <% end %>
    </div> <!-- index_post_container -->

  <% else %>
    <div class="message">
      <p class="red">Sorry!</p> <p class="inner_message">There are no pictures with the hashtag you entered. Click <%= link_to "here", search_path, class: "link"%> to search again.</p>
    </div>
  <% end %>
</div> <!-- centering_container -->