config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  get '/search', to: 'hashtags#search', as: 'search'
  resources :hashtags
  get '/search_result', to: 'hashtags#search_result', as: 'search_result'
  resources :hashtags
  post '/users/:user_id/pictures/:picture_id/likes/:icon_id', to: 'likes#create'
  get '/index', to: 'application#index'
  get '/users', to: 'users#redirect', as: 'redirect'
  resources :sessions, only: [:new, :create]
  delete '/sessions', to: 'sessions#destroy', as: 'destroy_session'
  get'/users/discover', to: 'users#discover', as: 'discover'
  get '/users/:id/followers', to: 'users#followers', as: "followers"
  get '/users/:id/followees', to: 'users#followees', as: "followees"

  get '/users/index', to: 'users#index'
  get '/users/login', to: 'users#login'
  get '/users/signup', to: 'users#signup'
  post '/users/check_user', to: 'users#check_user'

  # get '/users/user_information', to: 'users#user_information', as: 'info'
  resources :users do
    post '/followings', to: 'followings#create', as: 'create_following'
    delete '/followings', to: 'followings#destroy', as: 'unfollow'
    resources :pictures do
      resources :comments
      post '/likes', to: 'likes#create', as: 'create_like'
      resources :likes

    end
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :icons, through: :likes
  has_many :comments
  has_one_attached :img_url
  has_many :picture_hashtags
  has_many :hashtags, through: :picture_hashtags
  # validates :img_url, presence: true

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only:[:edit, :update, :destroy, :show]

  def new
    @picture = Picture.new
    @user = User.find(params[:user_id])
  end

  def create
#picturecaptionshtml
    @user = User.find(params[:user_id])
    # byebug
    @picture = Picture.new(description: params[:picture][:description], img_url: params[:picture][:img_url], user_id: params[:user_id])

    if @picture.save
      hashtag_check(@picture.description)
      @content_hashtags.each do |element|
        @hashtag = Hashtag.find_or_create_by(hashtag: element)
        PictureHashtag.create(hashtag_id: @hashtag.id, picture_id: @picture.id)
      end
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user_can_edit_picture = authorized_on_picture
    @comment = Comment.new
    @like = Like.new
    @likes = @picture.likes
  end

  def edit
  end

  def update
   if @picture.update(picture_params(:description))
     hashtag_check(@picture.description)
     @content_hashtags.each do |element|
       @hashtag = Hashtag.find_or_create_by(hashtag: element)
       PictureHashtag.create(hashtag_id: @hashtag.id, picture_id: @picture.id)
     end
     redirect_to "/users/#{@user.id}/pictures/#{@picture.id}"
   else
     render :edit
   end
  end

  def destroy
    @picture.destroy
    redirect_to @user
  end

  private

  def picture_params(*args)
    params.require(:picture).permit(*args)
  end

  def set_picture
    @user = User.find(params[:user_id])
    @picture = Picture.find(params[:id])

  end


end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/edit.erb
<div class="centering_container">
  <div class="form_container">
    <%= form_for [@user, @picture] do |f| %>
      <%= f.label :description, class: "message" %> <br>
      <%= f.text_field :description, class: "picture_edit_form_input"%>
      <%= f.submit "Edit Pic", class: "picture_edit_form_input"%>
    <% end %>
  </div>
</div>

app/views/pictures/new.erb
<%= form_for [@user, @picture] do |f| %>

<%= f.label "Picture" %>
<%= f.file_field :img_url%>
<%= f.label :description %>
<%= f.text_field :description%>
<%= f.submit "Post Pic"%>
<% end %>

app/views/pictures/show.erb
<div class="show_picture_container">
  <div class="picture_and_comments">


    <div class="picture_pic">

      <div class="picture">
        <%= image_tag @picture.img_url, :class => "picture" %>
      </div>

      <div class="picture_edit_delete">
        <% if @user_can_edit_picture %>
          <%= link_to "Edit", edit_user_picture_path  %>
          <%= button_to "Delete", [@user, @picture] , method: :delete %>
        <% end %>
      </div>
    </div>

    <div>
      <% Icon.all.each do |icon| %>

      <%= link_to icon.icon,  "/users/#{@user.id}/pictures/#{@picture.id}/likes/#{icon.id}", method: :post %>

      <% @number = @likes.select do |like|
      
         like.icon_id == icon.id
       end %>
       <%= @number.length %>




      <% end %>
    </div>

    <hr>
    <div class="picture_info">

      <div class="user_and_description">

          <%= link_to @user.username, @user, :class => "username" %>
          <div class="picture_description">
            <%= @picture.description %>
          </div>

      </div>

    <hr>
      <div class="comments_box">
          <% @picture.comments.each do |comment| %>
          <div class="user_of_comment">
            <%= link_to comment.user.username, comment.user, :class => "user_of_comment"%>
          </div>
          <div class="comment_of_user">
             : <%=comment.content %>
          </div>
        <% end %>
      </div>


      <%= form_for [@user, @picture, @comment] do |f| %>
      <div class="comment_input">
        <%= f.text_area :content, placeholder: "Leave a comment" %>
      </div>
      <%=  f.submit "Post"%>

      <% end %>
    </div>

  </div>
</div>